app:
  name: "PubFree Platform"
  version: "1.0.0"
  description: "一个免费的发布平台 - 生产环境"
  debug: false
  timezone: "Asia/Shanghai"

server:
  name: "pubfree-server"
  mode: "release"
  port: ":8080"
  read_timeout: 60s
  write_timeout: 60s
  max_header_mb: 1

database:
  driver: "mysql"
  host: "your-prod-db-host"
  port: 3306
  username: "prod_user"
  password: "your-super-secure-password"
  dbname: "pubfree_platform"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"
  max_idle_conns: 20
  max_open_conns: 200
  conn_max_lifetime: 300s
  log_mode: false

redis:
  host: "your-prod-redis-host"
  port: 6379
  password: "your-redis-password"
  db: 0
  pool_size: 20

jwt:
  secret: "your-production-jwt-secret-key-very-long-and-secure"
  expires_at: 24h
  issuer: "pubfree-platform"

logger:
  level: "info"
  format: "json"
  output: "file"
  filename: "logs/prod.log"
  max_size: 500
  max_age: 30
  max_backups: 10
  compress: true