app:
  name: "PubFree Platform Dev"
  version: "1.0.0-dev"
  description: "一个免费的发布平台 - 开发环境"
  debug: true
  timezone: "Asia/Shanghai"

server:
  name: "pubfree-server-dev"
  mode: "debug"
  port: ":8080"
  read_timeout: 60s
  write_timeout: 60s
  max_header_mb: 1

database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "root123"
  dbname: "pubfree_platform_dev"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"
  max_idle_conns: 5
  max_open_conns: 20
  conn_max_lifetime: 300s
  log_mode: true

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 1
  pool_size: 5

jwt:
  secret: "dev-jwt-secret-key"
  expires_at: 24h
  issuer: "pubfree-platform-dev"

logger:
  level: "debug"
  format: "text"
  output: "stdout"
  filename: "logs/dev.log"
  max_size: 10
  max_age: 7
  max_backups: 3
  compress: false
