app:
  name: "PubFree Platform"
  version: "1.0.0"
  description: "一个免费的发布平台"
  debug: false
  timezone: "Asia/Shanghai"

server:
  name: "pubfree-server"
  mode: "release"
  port: ":8080"
  read_timeout: 60s
  write_timeout: 60s
  max_header_mb: 1

database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  dbname: "pubfree_platform"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 300s
  log_mode: false

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10

jwt:
  secret: "your-super-secret-jwt-key-change-in-production"
  expires_at: 24h
  issuer: "pubfree-platform"

logger:
  level: "info"
  format: "json"
  output: "file"
  filename: "logs/app.log"
  max_size: 100
  max_age: 30
  max_backups: 5
  compress: true
