version: '3.8'

services:
  # 开发环境数据库
  mysql:
    image: mysql:8.0
    container_name: pubfree-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ../../scripts/init-dev.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    networks:
      - pubfree-dev-network

  # 开发环境Redis
  redis:
    image: redis:7-alpine
    container_name: pubfree-redis-dev
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    networks:
      - pubfree-dev-network

  # 开发环境后端服务
  pubfree-server:
    build: 
      context: ../../pubfree-server
      dockerfile: Dockerfile.dev
    container_name: pubfree-server-dev
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - mysql
      - redis
    environment:
      - APP_ENV=dev
      - GIN_MODE=debug
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE_TIME=${JWT_EXPIRE_TIME}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ../../pubfree-server:/app
      - dev_uploads:/app/uploads
    restart: unless-stopped
    networks:
      - pubfree-dev-network

  # 开发环境前端服务
  pubfree-web:
    build: 
      context: ../../pubfree-web
      dockerfile: Dockerfile.dev
    container_name: pubfree-web-dev
    ports:
      - "${WEB_PORT}:3000"
    depends_on:
      - pubfree-server
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_ENV=${VITE_ENV}
    volumes:
      - ../../pubfree-web:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - pubfree-dev-network

volumes:
  mysql_dev_data:
  redis_dev_data:
  dev_uploads:

networks:
  pubfree-dev-network:
    driver: bridge