version: '3.8'

services:
  # 开发环境数据库
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    container_name: pubfree-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ../../scripts/init-dev.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    networks:
      - pubfree-dev-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 60s

  # 开发环境Redis
  redis:
    image: redis:7-alpine
    platform: linux/amd64
    container_name: pubfree-redis-dev
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    networks:
      - pubfree-dev-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      timeout: 5s
      retries: 5
      interval: 30s
      start_period: 10s

  # 开发环境后端服务
  pubfree-server:
    build: 
      context: ../../pubfree-server
      dockerfile: Dockerfile.dev
      args:
        - BUILDPLATFORM=${BUILDPLATFORM:-linux/amd64}
        - TARGETPLATFORM=${TARGETPLATFORM:-linux/amd64}
        - TARGETOS=${TARGETOS:-linux}
        - TARGETARCH=${TARGETARCH:-amd64}
    platform: linux/amd64
    container_name: pubfree-server-dev
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - MODULE_NAME=pubfree-platform/pubfree-server
      - APP_ENV=dev
      - GIN_MODE=debug
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      # - JWT_SECRET=${JWT_SECRET}
      # - JWT_EXPIRE_TIME=${JWT_EXPIRE_TIME}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      # 只挂载配置文件，保护构建的二进制文件
      - ../../pubfree-server/configs:/app/configs:ro
      - ../../pubfree-server/dev-start.sh:/app/dev-start.sh:ro
      - dev_uploads:/app/uploads
      # - dev_logs:/app/logs
    restart: unless-stopped
    networks:
      - pubfree-dev-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 45s

  # 开发环境前端服务
  pubfree-web:
    build: 
      context: ../../pubfree-web
      dockerfile: Dockerfile.dev
    environment:
      - NODE_VERSION=20.19.0
      - NODE_ENV=development 
      - NODE_OPTIONS=--max-old-space-size=4096
      - VITE_API_TARGET=http://pubfree-server:8080
      - VITE_ENV=dev
    container_name: pubfree-web-dev
    ports:
      - "${WEB_PORT}:3000"
    depends_on:
      pubfree-server:
        condition: service_healthy
    volumes:
      # 挂载源代码，但保护 node_modules
      - ../../pubfree-web:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - pubfree-dev-network

volumes:
  mysql_dev_data:
    driver: local
  redis_dev_data:
    driver: local
  dev_uploads:
    driver: local
  dev_logs:
    driver: local

networks:
  pubfree-dev-network:
    driver: bridge